openapi: 3.0.0
info:
  version: 1.0.0
  title: Dalcetrapib ADCY9 Intepretation Recommender for rs1967309
  description: >-
    This object accepts as input two base pairs about a person for SNP rs1967309
    and returns a recommendation about Dalcetrapib
  license:
    name: GNU General Public License v3 (GPL-3)
    url: >-
      https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)#fulltext
  contact:
    name: KGrid Team
    email: kgrid-developers@umich.edu
    url: 'http://kgrid.org'
servers:
  - url: /99999/fk4n99hh99/v0.0.2
    description: Dalcetrapib ADCY9 Intepretation Recommender for rs1967309
tags:
  - name: KO Endpoints
    description: Dalcetrapib ADCY9 Intepretation Recommender for rs1967309 Endpoints
paths:
  /interpretProstateCancerRisk:
    post:
      tags:
        - KO Endpoints
      description: >-
        This object accepts as input two base pairs about a person for SNP
        rs1967309 and returns a recommendation about Dalcetrapib
      operationId: interp
      requestBody:
        description: inputs
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/input'
      responses:
        '200':
          description: response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/output'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'

components:
  schemas:
    input:
      required:
        - twoBases
      properties:
        twoBases:
          type: string
          enum:
            - AA
            - GA
            - GG
          example: AA
    output:
      required:
        - result
      properties:
        result:
          type: string
          example: >-
            Prescribe as needed. AA is accociated with a 39% decrease in
            cardiovascular events.
    error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
