openapi: 3.0.2
info:
  version: '1.0'
  title: 'Resource KO Example'
  description: An example of simple resource Knowledge Object
  license:
    name: GNU General Public License v3 (GPL-3)
    url: >-
      https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)#fulltext
  contact:
    name: KGrid Team
    email: kgrid-developers@umich.edu
    url: 'http://kgrid.org'
servers:
  - url: /resource/simple
    description: Hello world
tags:
  - name: KO Endpoints
    description: Hello world Endpoints
paths:
  /welcome:
    get:
      parameters:
        - in: query
          name: v
          schema:
            type: string
            default:
              $ref: '#/info/version'
          required: true
          description: the api version of the endpoint
      tags:
        - KO Endpoints
      description: Welcome.
      operationId: welcome-list
      responses:
        '200':
          description: response
          content:
            application/json:
              schema:
                $ref: 'https://demo.kgrid.org/schemas/openapischemas.yaml#/components/schemas/genericresponse'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: 'https://demo.kgrid.org/schemas/openapischemas.yaml#/components/schemas/genericerror'
