openapi: 3.0.0
info:
  version: '1.0'
  title: 'the best hello world ever'
  description: 'A native node js object run through the proxy adapter with multiple mime types'
  license:
    name: GNU General Public License v3 (GPL-3)
    url: >-
      https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)#fulltext
  contact:
    name: KGrid Team
    email: kgrid-developers@umich.edu
    url: 'http://kgrid.org'
servers:
  - url: /node/multimime
    description: Hello world
tags:
  - name: KO Endpoints
    description: Hello World Endpoints
paths:
  /welcome:
    post:
      parameters:
        - $ref: '#/components/parameters/apiversion'
      tags:
        - KO Endpoints
      description: Welcome.
      operationId: welcome
      requestBody:
        description: inputs
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/input'
      responses:
        '200':
          description: response
          content:
            application/json:
              schema:
                $ref: 'https://demo.kgrid.org/schemas/openapischemas.yaml#/components/schemas/genericresponse'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: 'https://demo.kgrid.org/schemas/openapischemas.yaml#/components/schemas/genericerror'
  /welcome-plain:
    post:
      parameters:
        - $ref: '#/components/parameters/apiversion'
      tags:
        - KO Endpoints
      description: Welcome.
      operationId: welcome-plain
      requestBody:
        description: inputs
        required: true
        content:
          text/plain:
            schema:
              $ref: '#/components/schemas/input-plain'
      responses:
        '200':
          description: response
          content:
            application/json:
              schema:
                $ref: 'https://demo.kgrid.org/schemas/openapischemas.yaml#genericresponse'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: 'https://demo.kgrid.org/schemas/openapischemas.yaml#genericerror'
components:
  parameters:
    apiversion:
      in: query
      required: false
      name: v
      schema:
        type: string
        default:
          $ref: '#/info/version'
  schemas:
    input:
      required:
        - name
      properties:
        name:
          type: string
          example: 'Bob'
    input-plain:
      type: string
      example: 'Mike Truk'
