openapi: 3.0.0
info:
  version: '1.0'
  title: 'Python Multiartifact KO example'
  description: 'A python object with a multiple artifacts'
servers:
  - url: /python/multiartifact/1.0
    description: Hello world
tags:
  - name: KO Endpoints
    description: Hello World Endpoints
paths:
  /welcome:
    post:
      tags:
        - KO Endpoints
      description: Welcome.
      operationId: welcome
      requestBody:
        description: inputs
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/user'
      responses:
        '200':
          description: response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/welcomeOutput'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
components:
  schemas:
    user:
      required:
        - name
        - spaces
        - size
      properties:
        name:
          type: string
          example: 'Severus'
        spaces:
          type: integer
          example: 100
        size:
          type: integer
          example: 20
    welcomeOutput:
      required:
        - result
      properties:
        result:
          type: string
          example: 'welcome'
    error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
