openapi: 3.0.2
info:
  version: '1.0'
  title: Sample Executive Object to be activated in the remote NodeJS runtime
  description: Executive Object to call context to retrieve executor
  license:
    name: GNU General Public License v3 (GPL-3)
    url: >-
      https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)#fulltext
  contact:
    name: KGrid Team
    email: kgrid-developers@umich.edu
    url: 'http://kgrid.org'
servers:
  - url: /node/executive
    description: Executive Object Example
paths:
  /process:
    post:
      parameters:
        - $ref: '#/components/parameters/apiversion'
      description: executive object
      operationId: process
      requestBody:
        description: inputs
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/input'
      responses:
        '200':
          description: response
          content:
            application/json:
              schema:
                $ref: 'https://demo.kgrid.org/schemas/openapischemas.yaml#/components/schemas/genericresponse'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: 'https://demo.kgrid.org/schemas/openapischemas.yaml#/components/schemas/genericerror'
components:
  parameters:
    apiversion:
      in: query
      required: false
      name: v
      schema:
        type: string
        default:
          $ref: '#/info/version'
  schemas:
    input:
      required:
        - name
        - height
        - weight
      properties:
        name:
          type: string
          example: 'Bob'
        height:
          type: number
          x-kgrid-unit: m
          example: 1.7
        weight:
          type: number
          x-kgrid-unit: kg
          example: 70.2
