openapi: 3.0.2
info:
  version: '1.0'
  title: Sample Executive Object to be activated in the remote NodeJS runtime
  description: Executive Object to call context to retrieve executor
servers:
  - url: /node/executive/1.0
    description: Executive Object Example
paths:
  /process:
    post:
      description: executive object
      operationId: process
      requestBody:
        description: inputs
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/input'
      responses:
        '200':
          description: response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/output'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: 'https://demo.kgrid.org/schemas/basicerror.yaml'

components:
  schemas:
    input:
      required:
        - name
        - height
        - weight
      properties:
        name:
          type: string
          example: 'Bob'
        height:
          type: number
          x-kgrid-unit: m
          example: 1.7
        weight:
          type: number
          x-kgrid-unit: kg
          example: 70.2
    output:
      required:
        - result
      properties:
        result:
          type: object
